name: omnisky
channels: [conda-forge]
dependencies:
  - python=3.11
  - lsdb>=0.9
  - hats>=0.9
  - astropy>=6.0
  - scipy>=1.13
  - astropy-healpix>=1.0
  - pyarrow>=16
  - pandas>=2.2
  - h5py>=3.11
  - s3fs>=2024.6
  - huggingface_hub>=0.24
  - datasets>=2.20
  - requests>=2.32
  - pytest>=8
  - mypy>=1.10
  - pip
